// src/constants/errorCodes.js
// 役割: APIエラーコードの定数定義

export const ERROR_CODES = {
  // 認証関連
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // 認可関連
  FORBIDDEN: 'FORBIDDEN',
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  PARENT_REQUIRED: 'PARENT_REQUIRED',
  CHILD_REQUIRED: 'CHILD_REQUIRED',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',
  
  // リソース関連
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CHILD_NOT_FOUND: 'CHILD_NOT_FOUND',
  RELATIONSHIP_NOT_FOUND: 'RELATIONSHIP_NOT_FOUND',
  
  // データ関連
  CONFLICT: 'CONFLICT',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  RELATIONSHIP_EXISTS: 'RELATIONSHIP_EXISTS',
  
  // バリデーション関連
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_EMAIL: 'INVALID_EMAIL',
  
  // ビジネスロジック関連
  CHILD_NOT_MANAGED: 'CHILD_NOT_MANAGED',
  RELATIONSHIP_ALREADY_EXISTS: 'RELATIONSHIP_ALREADY_EXISTS',
  RELATIONSHIP_PENDING: 'RELATIONSHIP_PENDING',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  
  // サーバー関連
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  
  // 特定機能関連
  CHAT_ERROR: 'CHAT_ERROR',
  LLM_ERROR: 'LLM_ERROR',
  EVALUATION_ERROR: 'EVALUATION_ERROR'
};

export const ERROR_MESSAGES = {
  [ERROR_CODES.AUTH_REQUIRED]: '認証が必要です',
  [ERROR_CODES.TOKEN_INVALID]: '無効なトークンです',
  [ERROR_CODES.TOKEN_EXPIRED]: 'トークンの有効期限が切れています',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'メールアドレスまたはパスワードが正しくありません',
  
  [ERROR_CODES.FORBIDDEN]: 'アクセス権限がありません',
  [ERROR_CODES.ADMIN_REQUIRED]: '管理者権限が必要です',
  [ERROR_CODES.PARENT_REQUIRED]: '保護者権限が必要です',
  [ERROR_CODES.CHILD_REQUIRED]: '子どもアカウントが必要です',
  [ERROR_CODES.ROLE_NOT_ALLOWED]: 'このロールでは実行できません',
  
  [ERROR_CODES.NOT_FOUND]: 'リソースが見つかりません',
  [ERROR_CODES.USER_NOT_FOUND]: 'ユーザーが見つかりません',
  [ERROR_CODES.CHILD_NOT_FOUND]: '子どもが見つかりません',
  [ERROR_CODES.RELATIONSHIP_NOT_FOUND]: '関係が見つかりません',
  
  [ERROR_CODES.CONFLICT]: 'データが競合しています',
  [ERROR_CODES.DUPLICATE_EMAIL]: 'このメールアドレスは既に使用されています',
  [ERROR_CODES.RELATIONSHIP_EXISTS]: 'この関係は既に存在します',
  
  [ERROR_CODES.VALIDATION_ERROR]: 'バリデーションエラーが発生しました',
  [ERROR_CODES.REQUIRED_FIELD_MISSING]: '必須項目が不足しています',
  [ERROR_CODES.INVALID_FORMAT]: '形式が正しくありません',
  [ERROR_CODES.INVALID_UUID]: '無効なID形式です',
  [ERROR_CODES.INVALID_EMAIL]: '無効なメールアドレス形式です',
  
  [ERROR_CODES.CHILD_NOT_MANAGED]: 'この子どもを管理する権限がありません',
  [ERROR_CODES.RELATIONSHIP_ALREADY_EXISTS]: '親子関係は既に存在します',
  [ERROR_CODES.RELATIONSHIP_PENDING]: '関係が承認待ちです',
  [ERROR_CODES.PROFILE_NOT_FOUND]: 'プロフィールが見つかりません',
  
  [ERROR_CODES.INTERNAL_ERROR]: 'サーバー内部でエラーが発生しました',
  [ERROR_CODES.DATABASE_ERROR]: 'データベースエラーが発生しました',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: '外部サービスでエラーが発生しました',
  
  [ERROR_CODES.CHAT_ERROR]: 'チャット処理中にエラーが発生しました',
  [ERROR_CODES.LLM_ERROR]: 'AI処理中にエラーが発生しました',
  [ERROR_CODES.EVALUATION_ERROR]: '評価処理中にエラーが発生しました'
};